const jobDetails = [
    {CompanyName:"MICROSOFT", Designation:"Frontend developer", DatePosted:"12/01/2018", details: "Click for Details",
    message: "This recruitment is for Microsoft"},
    {CompanyName:"GOOGLE", Designation:"Backend developer", DatePosted:"01/01/2020", details: "Click for Details"},
    {CompanyName:"YAHOO", Designation:"Sales Manager", DatePosted:"12/01/2019", details: "Click for Details"},
    {CompanyName:"RED HAT", Designation:"VP ENgineering", DatePosted:"12/01/2019", details: "Click for Details"},
    {CompanyName:"SWIGGY", Designation:"Chief of Staff", DatePosted:"12/02/2019", details: "Click for Details"},
    {CompanyName:"ZOMATO", Designation:"Technical Lead", DatePosted:"12/03/2019", details: "Click for Details"},
    {CompanyName:"GOOGLE", Designation:"Backend developer", DatePosted:"01/01/2020", details: "Click for Details"},
    {CompanyName:"OYO", Designation:"Mobile Developer", DatePosted:"12/06/2019", details: "Click for Details"},
    {CompanyName:"ZUNIPER", Designation:"Test Engineer", DatePosted:"12/05/2019", details: "Click for Details"},
    {CompanyName:"MICROSOFT", Designation:"Frontend developer", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"MYNTRA", Designation:"Backend developer", DatePosted:"12/01/2019", details: "Click for Details"},
    {CompanyName:"FLIPKART", Designation:"Technical Lead", DatePosted:"12/09/2019", details: "Click for Details"},
    {CompanyName:"UBER INDIA", Designation:"Test Engineer", DatePosted:"12/07/2019", details: "Click for Details"},
    {CompanyName:"OLA INDIA", Designation:"VP ENgineering", DatePosted:"12/08/2019", details: "Click for Details"},
    {CompanyName:"GOOGLE", Designation:"Backend developer", DatePosted:"01/01/2020", details: "Click for Details"},
    {CompanyName:"MEESHO", Designation:"Test Engineer", DatePosted:"12/11/2019", details: "Click for Details"},
    {CompanyName:"UDAAN", Designation:"Chief of Staff", DatePosted:"12/010/2019", details: "Click for Details"},
    {CompanyName:"MICROSOFT", Designation:"Frontend developer", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"SYNTEL", Designation:"Technical Lead", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"WIPRO", Designation: "Technical Lead", DatePosted:"12/04/2018", details: "Click for Details"},
    {CompanyName:"INFOSYS", Designation:"Backend developer", DatePosted:"12/06/2018", details: "Click for Details"},
    {CompanyName:"TECH MAHINDRA", Designation:"Test Engineer", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"WALMART", Designation:"Test Engineer", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"CISCO", Designation:"Technical Lead", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"CONNECTECHO", Designation:"Mobile Developer", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"GOOGLE", Designation:"Backend developer", DatePosted:"01/01/2020", details: "Click for Details"},
    {CompanyName:"ANNATA DESIGN", Designation:"Chief of Staff", DatePosted:"12/01/2019", details: "Click for Details"},
    {CompanyName:"MICROSOFT", Designation:"Frontend developer", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"BLACK BUCK", Designation:"Mobile Developer", DatePosted:"12/01/2020", details: "Click for Details"},
    {CompanyName:"HOTSTAR", Designation:"Chief of Staff", DatePosted:"12/04/2019", details: "Click for Details"},
    {CompanyName:"NETFLIX", Designation:"Backend developer", DatePosted:"12/05/2019", details: "Click for Details"},
    {CompanyName:"AIR INDIA", Designation:"Test Engineer", DatePosted:"12/06/2019", details: "Click for Details"},
    {CompanyName:"BOUNCE", Designation:"Backend developer", DatePosted:"12/07/2019", details: "Click for Details"},
    {CompanyName:"GOOGLE", Designation:"Backend developer", DatePosted:"01/08/2020", details: "Click for Details"},
    {CompanyName:"RAPIDO", Designation:"Test Engineer", DatePosted:"11/01/2018", details: "Click for Details"},
    {CompanyName:"BIG BASKET", Designation:"Test Engineer", DatePosted:"09/01/2018", details: "Click for Details"},
    {CompanyName:"SUPER DAILY", Designation:"Chief of Staff", DatePosted:"09/01/2018", details: "Click for Details"},
    {CompanyName:"FOODPANDA", Designation:"Mobile Developer", DatePosted:"06/01/2018", details: "Click for Details"},
    {CompanyName:"MICROSOFT", Designation:"Frontend developer", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"BEWAKOOF.COM", Designation:"Test Engineer", DatePosted:"12/01/2018", details: "Click for Details"},
    {CompanyName:"CASHKARO", Designation:"Backend developer", DatePosted:"12/01/2019", details: "Click for Details"},
    {CompanyName:"COUPONDUNIYA", Designation:"Test Engineer", DatePosted:"12/01/2020", details: "Click for Details"}
];

export default jobDetails;